technical_name: heatmap_kepuasan_departemen_periode_k3c3
title: "Heatmap: Skor Kepuasan per Departemen x Periode"
description: >
  Peta panas rata-rata skor kepuasan per departemen per periode.
type:
  kind: heatmap
  mv: mv_analisis_kepuasan_karyawan
dataset:
  schema: public
  table: mv_analisis_kepuasan_karyawan
query:
  group_by: [departemen, periode]
  metrics:
    - { name: avg_skor, expr: "AVG(skor_kepuasan)" }
  row_limit: 20000
encoding:
  x: { field: periode, type: temporal }
  y: { field: departemen, type: nominal }
  color: { field: avg_skor, type: quantitative }
presentation:
  number_format: "0.0"
assets:
  png_url: "./sample/heatmap_kepuasan_departemen_periode_k3c3.png"
