name: generate-sql

on:
  workflow_dispatch:
    inputs:
      schema:
        description: "Nama schema database"
        required: true
        default: "public"
      owner:
        description: "Owner dari table (opsional)"
        required: false
        default: ""
      with_drop:
        description: "Drop table jika sudah ada (true/false)"
        required: false
        default: "false"
      default_varchar_length:
        description: "Default length untuk kolom varchar/char tanpa length"
        required: false
        default: "255"
      tablespace:
        description: "Tablespace (opsional)"
        required: false
        default: ""
      create_extensions:
        description: "Ekstensi yang akan dibuat (mis. pgcrypto)"
        required: false
        default: "pgcrypto"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Generate SQL
        run: |
          python scripts/generate_sql_from_yaml.py \
            --src struktur_data \
            --schema "${{ github.event.inputs.schema }}" \
            --owner "${{ github.event.inputs.owner }}" \
            --with-drop "${{ github.event.inputs.with_drop }}" \
            --default-varchar-length "${{ github.event.inputs.default_varchar_length }}" \
            --tablespace "${{ github.event.inputs.tablespace }}" \
            --create-extensions "${{ github.event.inputs.create_extensions }}" \
            > build.sql

      - name: Upload build.sql
        uses: actions/upload-artifact@v4
        with:
          name: build-sql
          path: build.sql

      - name: Tulis ringkasan
        run: |
          echo "### Build SQL sukses ✅" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Schema: ${{ github.event.inputs.schema }}" >> $GITHUB_STEP_SUMMARY
          echo "Owner: ${{ github.event.inputs.owner }}" >> $GITHUB_STEP_SUMMARY
          echo "With Drop: ${{ github.event.inputs.with_drop }}" >> $GITHUB_STEP_SUMMARY
          echo "Default varchar length: ${{ github.event.inputs.default_varchar_length }}" >> $GITHUB_STEP_SUMMARY
          echo "Tablespace: ${{ github.event.inputs.tablespace }}" >> $GITHUB_STEP_SUMMARY
          echo "Extensions: ${{ github.event.inputs.create_extensions }}" >> $GITHUB_STEP_SUMMARY
