name: Generate SQL (panduan_struktur_data)

on:
  workflow_dispatch:
    inputs:
      schema:
        description: "Nama schema target (default: public)"
        required: false
        default: "public"
      owner:
        description: "Owner default untuk objek (opsional)"
        required: false
        default: ""
      with_drop:
        description: "Sisipkan DROP IF EXISTS sebelum CREATE"
        required: false
        default: "false"
      default_varchar_length:
        description: "Panjang default VARCHAR jika tidak ditentukan"
        required: false
        default: "255"
      tablespace:
        description: "Tablespace (opsional)"
        required: false
        default: ""
      create_extensions:
        description: "Daftar ekstensi yang akan dibuat (comma-separated), mis. 'pgcrypto,uuid-ossp'"
        required: false
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Generate SQL
        run: |
          python scripts/generate_sql_from_yaml.py \
            --struktur-dir "struktur_data" \
            --out "build.sql" \
            --schema "${{ github.event.inputs.schema }}" \
            --owner "${{ github.event.inputs.owner }}" \
            --with-drop "${{ github.event.inputs.with_drop }}" \
            --default-varchar-length "${{ github.event.inputs.default_varchar_length }}" \
            --tablespace "${{ github.event.inputs.tablespace }}" \
            --create-extensions "${{ github.event.inputs.create_extensions }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-sql
          path: build.sql

      - name: Job summary
        if: always()
        run: |
          echo "### Generate SQL Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Schema: \`${{ github.event.inputs.schema }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Owner: \`${{ github.event.inputs.owner || 'N/A' }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- With DROP: \`${{ github.event.inputs.with_drop }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Default varchar length: \`${{ github.event.inputs.default_varchar_length }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Tablespace: \`${{ github.event.inputs.tablespace || 'N/A' }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Create extensions: \`${{ github.event.inputs.create_extensions || 'N/A' }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Artifact **build-sql** berisi file \`build.sql\`." >> $GITHUB_STEP_SUMMARY
